name: Playwright Tests
on:
  schedule:
    - cron: "0 0 * * *" # Run at the end of every day
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Playwright E2E tests
    timeout-minutes: 7
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.30.0-jammy
    env:
      BASEURL: https://marcusfelling.com
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm ci

      - name: Run Playwright tests
        run: |
          HOME=/root npx playwright test

      - name: Create test summary
        uses: test-summary/action@dist
        if: always()
        with:
          paths: ./test-results/junit.xml

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./playwright-report/
          retention-days: 30
